In [2]:
import numpy as np

arr = np.arange(20)

print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [3]:
print(arr.reshape(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [4]:
print(arr.reshape(5,-1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [5]:
ar1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar1)
print(ar1.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [6]:
ar1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [7]:
np.reshape([0,1,2,3,4,5,6,7,8,9,10,11], (-1,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [9]:
ar2 = np.array([10,20,30,40],dtype='int16')

print(ar2.dtype)
print(ar2.itemsize)
print(ar2.nbytes)

int16
2
8


In [10]:
ar3 = np.array([2.8,5.1,9.7])
print(ar3.astype('int32'))

[2 5 9]


In [12]:
ar4 = np.array([1,2,3])

print(ar4.astype('float32'))
print(ar4.astype('bool'))

[1. 2. 3.]
[ True  True  True]


In [16]:
arr = np.arange(1,21)
print(arr[arr > 10])

[11 12 13 14 15 16 17 18 19 20]


In [17]:
print(arr[arr % 2 == 0])

[ 2  4  6  8 10 12 14 16 18 20]


In [18]:
arr[arr > 15] = 100
print(arr)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15 100 100 100
 100 100]


In [19]:
len(arr[arr % 3 == 0])

5

In [23]:
arr = np.array([8,3,9,1,6])
print(np.sort(arr)[::-1])
print(np.sort(arr))

[9 8 6 3 1]
[1 3 6 8 9]


In [24]:
print(np.sort(arr)[-3:])

[6 8 9]


In [26]:
print(np.argsort(arr))

[3 1 4 0 2]


In [27]:
cities = np.array([
    "Delhi",
    "Mumbai",
    "Pune",
    "Bengaluru"
])

population = np.array([
    20,
    12,
    7,
    13
])

cities[population.argsort()]

array(['Pune', 'Mumbai', 'Bengaluru', 'Delhi'], dtype='<U9')

In [28]:
scores = np.array([75,92,81,68,99,88])
print(scores[scores.argsort()[-3:]])

[88 92 99]
