In [2]:
import numpy as np

In [3]:
arr = np.array([5,10,15,20,25])
print(arr)
print(type(arr))

[ 5 10 15 20 25]
<class 'numpy.ndarray'>


In [4]:
print(arr * 10)

[ 50 100 150 200 250]


In [5]:
a = np.array([2,4,6,8])
print(a + 5)

[ 7  9 11 13]


In [6]:
np.full(5,100)

array([100, 100, 100, 100, 100])

In [7]:
np.zeros((4,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.full((3, 3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

##### arange(start,stop,step)  You know the step size
##### linspace(start,stop,step) You know how many values you need
##### logspace(start,stop,step) You need logarithmic spacing (10^0 10^1 10^2)

In [10]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0, 30, 5)

array([ 0,  5, 10, 15, 20, 25])

In [12]:
np.linspace(0, 100, 21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [18]:
np.logspace(0, 5,5)

array([1.00000000e+00, 1.77827941e+01, 3.16227766e+02, 5.62341325e+03,
       1.00000000e+05])

In [21]:
np.arange(100,0,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [23]:
matrix = np.array([[1,2,3,4,5],
          [4,5,6,7,8]])

print(matrix.shape)
print(matrix.ndim)
print(matrix.size)
print(len(matrix))

(2, 5)
2
10
2


In [25]:
ze = np.zeros((2,3,4))

print(ze.shape)
print(ze.ndim)
print(ze.size)
print(len(ze))

(2, 3, 4)
3
24
2


In [26]:
a = np.ones((4,6))

print(a.shape)

print(a.ndim)

print(a.size)

print(len(a))

(4, 6)
2
24
4
