In [2]:
import numpy as np

arr = np.arange(20)

print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [3]:
print(arr.reshape(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [4]:
print(arr.reshape(5,-1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [5]:
ar1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar1)
print(ar1.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [6]:
ar1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [7]:
np.reshape([0,1,2,3,4,5,6,7,8,9,10,11], (-1,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [9]:
ar2 = np.array([10,20,30,40],dtype='int16')

print(ar2.dtype)
print(ar2.itemsize)
print(ar2.nbytes)

int16
2
8


In [10]:
ar3 = np.array([2.8,5.1,9.7])
print(ar3.astype('int32'))

[2 5 9]


In [12]:
ar4 = np.array([1,2,3])

print(ar4.astype('float32'))
print(ar4.astype('bool'))

[1. 2. 3.]
[ True  True  True]


In [16]:
arr = np.arange(1,21)
print(arr[arr > 10])

[11 12 13 14 15 16 17 18 19 20]


In [17]:
print(arr[arr % 2 == 0])

[ 2  4  6  8 10 12 14 16 18 20]


In [18]:
arr[arr > 15] = 100
print(arr)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15 100 100 100
 100 100]


In [19]:
len(arr[arr % 3 == 0])

5

In [23]:
arr = np.array([8,3,9,1,6])
print(np.sort(arr)[::-1])
print(np.sort(arr))

[9 8 6 3 1]
[1 3 6 8 9]


In [24]:
print(np.sort(arr)[-3:])

[6 8 9]


In [26]:
print(np.argsort(arr))

[3 1 4 0 2]


In [27]:
cities = np.array([
    "Delhi",
    "Mumbai",
    "Pune",
    "Bengaluru"
])

population = np.array([
    20,
    12,
    7,
    13
])

cities[population.argsort()]

array(['Pune', 'Mumbai', 'Bengaluru', 'Delhi'], dtype='<U9')

In [28]:
scores = np.array([75,92,81,68,99,88])
print(scores[scores.argsort()[-3:]])

[88 92 99]


In [32]:
arr = np.arange(10)
arr[[2,5,8]]

array([2, 5, 8])

In [33]:
marks = np.array([35,82,91,44,67])
np.where(marks >= 50, "Pass", "Fail")

array(['Fail', 'Pass', 'Pass', 'Fail', 'Pass'], dtype='<U4')

In [35]:
matrix = np.arange(1,17).reshape(4,4)
print(matrix[[1,3],[1,3]])

[ 6 16]


In [36]:
conditions = [
    marks >= 90,
    marks >= 75,
    marks >= 60
]

choices = [
    "A",
    "B",
    "C"
]

grades = np.select(
    conditions,
    choices,
    default="D"
)

print(grades)

['D' 'B' 'A' 'D' 'C']


In [37]:
arr = np.arange(10)
np.where(arr %2 ==0,0,1)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [38]:
temps = np.array([-20,-5,10,25,48])
np.clip(temps,0,40)

array([ 0,  0, 10, 25, 40])

In [39]:
marks = np.array([95,83,74,61,48])

conditions = [
    marks >= 90,
    marks >= 75,
    marks >= 60
]

choices = [
    "A",
    "B",
    "C"
]

np.select(conditions, choices, default="D")

array(['A', 'B', 'C', 'C', 'D'], dtype='<U1')

In [40]:
salary = np.array([30000,45000,60000,80000])
np.where(salary >= 50000, "Senior", "Junior")

array(['Junior', 'Junior', 'Senior', 'Senior'], dtype='<U6')

In [46]:
students = np.array([
    "Alice",
    "Bob",
    "Charlie",
    "David",
    "Emma"
])

marks = np.array([
    92,
    74,
    61,
    45,
    88
])


grades = np.select(conditions, choices, default="D")
labels = np.where(marks > 50,"Pass","Fail")
bin_labels = np.where(labels == "Pass", 1, 0)

np.array([students,marks,grades,labels,bin_labels]).T


array([['Alice', '92', 'A', 'Pass', '1'],
       ['Bob', '74', 'B', 'Pass', '1'],
       ['Charlie', '61', 'C', 'Pass', '1'],
       ['David', '45', 'C', 'Fail', '0'],
       ['Emma', '88', 'D', 'Pass', '1']], dtype='<U21')