In [3]:
import numpy as np

In [9]:
arr = np.array([5,10,15,20,25])
print(arr)
print(type(arr))

[ 5 10 15 20 25]
<class 'numpy.ndarray'>


In [10]:
print(arr * 10)

[ 50 100 150 200 250]


In [13]:
a = np.array([2,4,6,8])
print(a + 5)

[ 7  9 11 13]


In [14]:
np.full(5,100)

array([100, 100, 100, 100, 100])

In [17]:
np.zeros((4,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [18]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])