# Load Numpy

In [2]:
import numpy as np


In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[1,2,3.0],[1.2,3.4,4.5]])
print(b)

[[1.  2.  3. ]
 [1.2 3.4 4.5]]


In [ ]:
#Get dimensions 
a.ndim
b.ndim

#Get Shape
b.shape # (R,C)

(2, 3)

In [16]:
#Get dtype
a.dtype

dtype('int64')

In [17]:
#get size
b.itemsize

8

In [ ]:
# Get Total Size
b.size

6

In [23]:
#get total size
b.itemsize * b.size
b.nbytes

48

# Accessing / Changing elements

In [24]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
a.shape

(2, 7)

In [28]:
#get specific element
a[1,5]

np.int64(13)

In [29]:
#Get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
#get specific colun
a[:,0]

array([1, 8])

In [31]:
#Getting a little fancy with fetching elements
a[0, 1:6:2]

array([2, 4, 6])

In [32]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [33]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


### 3d example

In [34]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [37]:
b[0,1,1]

np.int64(4)