# Initialize Different types of arrays

In [1]:
import numpy as np

In [7]:
#full zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [9]:
a = np.full((2,2),99)
print(a)

[[99 99]
 [99 99]]


In [11]:
# any other number full_like shape of a
np.full_like(a,4)

array([[4, 4],
       [4, 4]])

In [13]:
#random numbers default decimals
np.random.rand(4,2)

array([[0.97592817, 0.58250491],
       [0.94305945, 0.01399464],
       [0.49015074, 0.22404176],
       [0.44048593, 0.60443245]])

In [16]:
#random integer from 0-7
np.random.randint(0,8,size=(3,3))

array([[2, 2, 6],
       [2, 6, 7],
       [7, 4, 7]])

In [18]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
arr = np.array([[1,2,3]])
ri = np.repeat(arr,3,axis=0)
print(ri)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [29]:
output = np.ones((5,5))
print(output)

zeros = np.zeros((3,3))
zeros[1,1] = 9
print(zeros)

output[1:4,1:4] = zeros
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful with copying arrays

In [31]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


# Mathematics

In [32]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [33]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [34]:
b = np.array([1,0,1,0])
print(a + b)

[2 2 4 4]


In [35]:
print(a ** 2)

[ 1  4  9 16]


In [37]:
# take sin of all

np.sin(a)

np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Linear Algebra

In [38]:
a = np.full((2,3),1)
print(a)

b = np.full((3,2),2)
print(b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


In [40]:
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

In [41]:
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

# Reorganizing array

In [42]:
before = np.array([[1,2,3],[4,5,6]])
after = before.reshape((3,2))
print(before)
print(after)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [43]:
# vertical stack
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
#horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Load data from file

In [49]:
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


#### Boolean masking and Advance indexing

In [51]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

### Indexing with list in Numpy works|

In [55]:
test1 = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20],[21,22,23,24,25,26,27,28,29,30]]).reshape(6,5)

print(test1[2:4,0:2])

[[11 12]
 [16 17]]


In [56]:
print(test1[[0,1,2,3],[1,2,3,4]])

[ 2  8 14 20]


In [62]:
test1[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])